---
apiVersion: cli.kyverno.io/v1alpha1
kind: Test
metadata:
  name: strict-cilium-network-policy
policies:
  - ../restrictions.yaml
resources:
  - resources.yaml
results:
  - kind: CiliumNetworkPolicy
    policy: cilium-ensure-servername-for-fqdns
    resources:
      - bad-no-sni-check
      - bad-partial-sni-check
      - bad-wrong-sni-check
      - bad-no-servernames
      - bad-no-sni-check-443
    result: fail
    rule: validate-servername-for-fqdns
  - kind: CiliumNetworkPolicy
    policy: cilium-ensure-servername-for-fqdns
    resources:
      - good-with-sni-check
      - good-with-sni-check-simple
      - good-with-sni-check-list
      - good-with-no-sni-need-check
      - good-with-sni-check-443
    result: pass
    rule: validate-servername-for-fqdns
